networks:
  default:
    external:
      name: roboshop

services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    networks:
      - default

  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
    networks:
      - default

  web:
    image: web:v1
    container_name: web
    ports:
      - "8080:80"
    depends_on:
      - catalogue
    networks:
      - default

redis:


user:
 image: user:v1
 container-name: user
 depends_on:
   - redis
   - mongodb



        
    